//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuissnessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public int account_id { get; set; }
        public string cust_name { get; set; }
        public string acc_type { get; set; }
        public int balance { get; set; }
    }
}
